version: '2'
services:
  app:
    image: aksmj8855/simple_profile
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - FLASKS3_BUCKET_NAME=
      - MYSQL_HOST=
      - MYSQL_PORT=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=
  rproxy:
    image: library/nginx
    depends_on:
      - app
    links:
      - app
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf